### ISSUE TITLE
from qibo import models error?

### ISSUE THREAD

**Issue by DiegoGM91** [Quantum-TII/qibo#225]
`from qibo import models` in the 0.0.1b4 version  throws:

```
Traceback (most recent call last):

  File "<ipython-input-6-0ba8bc11d61b>", line 1, in <module>
    runfile('/home/diego/Escritorio/prueba_qaoa.py', wdir='/home/diego/Escritorio')

  File "/home/diego/VE_Quantum/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/diego/VE_Quantum/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/diego/Escritorio/prueba_qaoa.py", line 9, in <module>
    from qibo import models

  File "/home/diego/VE_Quantum/lib/python3.7/site-packages/qibo/__init__.py", line 2, in <module>
    from qibo.config import set_precision, set_backend, set_device, get_backend, get_precision, get_device, matrices, K

  File "/home/diego/VE_Quantum/lib/python3.7/site-packages/qibo/config.py", line 53, in <module>
    'DTYPEINT': tf.int64,

AttributeError: module 'tensorflow' has no attribute 'int64'
```

**Comment by DiegoGM91** [comment]
I have TensorFlow 2.2.0

**Comment by scarrazza** [comment]
I cannot reproduce this issue. Could you please try:
```python
import tensorflow as tf
print(tf.__version__)
tf.int64
```

**Comment by DiegoGM91** [comment]
I'm not able to reproduce it myself either. I just opened a new terminal and the issue disappeared.

No idea what happened. Sorry for the spam!
