### ISSUE TITLE
Memory error with the noisy circuit

### ISSUE THREAD

**Issue by GoGoKo699** [Quantum-TII/qibo#331]
I got this error message while running a 30-qubits Shor example with noise. 
The problem happened during the first measurement.
The 29-qubits code is still running.

```
Traceback (most recent call last):
  File "DGX2.py", line 57, in <module>
    w=Shor_Error2(N,a,Xerror,Zerror)
  File "DGX2.py", line 45, in Shor_Error2
    result = noisy_c(nshots=1000)
  File "/home/tii/qibo/src/qibo/abstractions/circuit.py", line 707, in __call__
    return self.execute(initial_state=initial_state, nshots=nshots)
  File "/home/tii/qibo/src/qibo/core/circuit.py", line 226, in execute
    return self._repeated_execute(nshots, initial_state)
  File "/home/tii/qibo/src/qibo/core/circuit.py", line 179, in _repeated_execute
    state.measure(self.measurement_gate, nshots=1)
  File "/home/tii/qibo/src/qibo/core/states.py", line 84, in measure
    self.measurements = gate(self, nshots)
  File "/home/tii/qibo/src/qibo/core/cgates.py", line 277, in __call__
    probs = state.probabilities(measurement_gate=self)
  File "/home/tii/qibo/src/qibo/core/states.py", line 73, in wrapper
    return func(self, qubits=set(qubits)) # pylint: disable=E1102
  File "/home/tii/qibo/src/qibo/core/states.py", line 80, in probabilities
    state = K.reshape(K.square(K.abs(self.tensor)), self.nqubits * (2,))
  File "/home/tii/qibo/src/qibo/backends/tensorflow.py", line 98, in square
    return self.backend.square(x)
  File "/home/tii/miniconda3/envs/qibo/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10157, in square
    _ops.raise_from_not_ok_status(e, name)
  File "/home/tii/miniconda3/envs/qibo/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1073741824] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Square]
```

Here attached the code.

[Issue.zip](https://github.com/Quantum-TII/qibo/files/6035762/Issue.zip)

**Comment by scarrazza** [comment]
@GoGoKo699 I had a chat with @stavros11, and we believe you are running on the dgx qibo env, where we have installed a development branch. I will create a separate account for you so we avoid this issues in the future, and install everything from master or pip.

**Comment by GoGoKo699** [comment]
Ok, thank you!
